export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_GITAPI_ORG_SUCCESS = 'GET_GITAPI_ORG_SUCCESS';
export const GET_GITAPI_REPO_LIST_SUCCESS = 'GET_GITAPI_REPO_LIST_SUCCESS';
export const GET_GITAPI_COMMIT_LIST_SUCCESS = 'GET_GITAPI_COMMIT_LIST_SUCCESS';